<title>All Tasks</title>
<body style="font-family: 'Roboto Light', sans-serif; background-color: #ffffff; margin: 0; padding: 20px; color: #e0e0e0;background: #262626 ">
<div style="max-width: 3fr; margin: 0 auto; background-color: #e6e6e6; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.3); padding: 20px;">
    <div style="display: flex; justify-content: center; max-width: 3fr; margin: 0 auto; background-color: #262626; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.3); padding: 20px;">
        <h1 style="text-align: center" aria-label="Title: Tasks">Tasks</h1>
    </div>
    <br>
    <div style="display: flex; justify-content: center; max-width: 3fr; margin: 0 auto; background-color: #262626; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.3); padding: 20px;">
        <form style="margin: 20px; text-align: center" aria-label="Task Creation Form" action="/tasks"
              method="post">
            <label for="text_input" aria-label="New Task Details Label">New Task Details: </label>
            <input id='text_input' name='task_input' type="text">
            <input type="submit" value="Create Task">
        </form>
    </div>
    <br>
    <div class="TableContainer" style="display: flex; justify-content: center;">
        <table aria-label="Tasks Table"
               style="background: #333333; border-spacing: 20px; border-collapse: collapse;font-size: 18px;width: 100%;border: solid 1px black;border-radius: 8px">
            <tr style="background: #333333; margin: 5px; text-align: center; border: 1px solid black;">
                <th aria-label="Tasks Header">Task</th>
                <th aria-label="Completed Indicator">Status</th>
                <th aria-label="Complete Button">Complete</th>
                <th aria-label="Delete Button">Delete</th>
                <th aria-label="Edit Input">Update Details</th>
            </tr>
            <?php
            foreach ($tasksData as $task) {
                $status = ($task['completed'] === 0) ? 'Active' : 'Complete';
                echo "<tr style='text-align: center'>";
                echo "<td aria-label='Task Details'>" . $task['task'] . "</td>";
                echo "<td aria-label='Task Status'>" . $status . "</td>";
                echo "<td aria-label='Task Complete Button'><form method='post' action='/tasks/complete'><input type='submit' name='" . $task['id'] . "' value='&#10003;'></form></td>";
                echo "<td aria-label='Task Delete Button'><form method='post' action='/tasks/delete'><input type='submit' name='" . $task['id'] . "' value='&#128465;'></form></td>";
                echo "<td aria-label='Task Edit Input'><form method='post' action='/tasks/edit'><input type='text' name='" . $task['id'] . "' aria-label='Edit Text Input'><input type='submit' value='update' aria-label='Edit Update Button'></form></td>";
                echo "</tr>";
            }
            ?>
        </table>
    </div>
</div>
</body>
<footer style="display: flex; justify-content: space-evenly; align-items: center">
    <p>Created and Designed by Carl Ollington</p>
    <p>Get that work done!</p>
    <a href="/" style="text-decoration: none; color: whitesmoke">Home</a>
</footer>